name: 1. Integration Check with PHPUnit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  integration-check:
    name: Integration Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer, phpunit
        
    - name: Create minimal composer.json
      run: |
        cat > composer.json << 'EOF'
        {
          "require-dev": {
            "phpunit/phpunit": "^10.0"
          }
        }
        EOF
        
    - name: Install PHPUnit
      run: composer install --no-interaction
      
    - name: Create simple PHPUnit test
      run: |
        mkdir -p tests
        cat > tests/SecurityTest.php << 'EOF'
        <?php
        use PHPUnit\Framework\TestCase;
        
        class SecurityTest extends TestCase
        {
            public function testXSSValidation()
            {
                // Simple XSS test
                $input = '<script>alert("xss")</script>';
                $this->assertTrue(preg_match('/<script/i', $input) === 1, 'XSS pattern detected');
                echo "✅ XSS validation test passed\n";
            }
            
            public function testSQLInjectionValidation()
            {
                // Simple SQL injection test
                $input = "' OR 1=1--";
                $this->assertTrue(preg_match("/or\\s+1\\s*=\\s*1/i", $input) === 1, 'SQL injection pattern detected');
                echo "✅ SQL injection validation test passed\n";
            }
            
            public function testSafeInput()
            {
                // Test safe input
                $input = 'hello world';
                $this->assertTrue(strlen($input) > 0, 'Safe input processed');
                echo "✅ Safe input test passed\n";
            }
        }
        EOF
        
    - name: Create PHPUnit configuration
      run: |
        cat > phpunit.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <phpunit bootstrap="vendor/autoload.php" colors="true">
          <testsuites>
            <testsuite name="Security Tests">
              <directory>tests</directory>
            </testsuite>
          </testsuites>
        </phpunit>
        EOF
        
    - name: Run PHPUnit tests
      run: |
        ./vendor/bin/phpunit
        echo "✅ Integration check completed successfully"