ui_security_tests:
  stage: ui_test
  image: php:8.2-cli
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium
  
  variables:
    # Use the service alias for Selenium
    SELENIUM_HOST: "selenium"
    SELENIUM_PORT: "4444"
    # Use localhost since tests run in the same container as the app
    APP_URL: "http://localhost:8080"
  
  before_script:
    # Install dependencies
    - apt-get update && apt-get install -y git unzip wget
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install --no-interaction --prefer-dist
    
    # Start PHP built-in server in background
    - php -S 0.0.0.0:8080 -t public/ &
    - sleep 5  # Give server time to start
    
    # Wait for Selenium to be ready
    - |
      echo "Waiting for Selenium..."
      for i in {1..30}; do
        if wget -q --spider http://selenium:4444/wd/hub/status; then
          echo "Selenium is ready!"
          break
        fi
        echo "Waiting for Selenium... ($i/30)"
        sleep 2
      done
  
  script:
    # Run your Selenium tests
    - php vendor/bin/phpunit tests/SeleniumTest.php
  
  after_script:
    # Kill the PHP server
    - pkill -f "php -S" || true
  
  artifacts:
    when: always
    paths:
      - tests/logs/
      - screenshots/
    expire_in: 1 week
  
  only:
    - main
    - develop
    - merge_requests